root: true

parserOptions:
    ecmaVersion: "latest"

env:
    es6: true
    node: true

extends:
    "eslint:all"

rules:
    array-bracket-newline: ["error", "consistent"]
    arrow-parens: ["error", "as-needed"]
    func-style: ["error", "declaration"]
    function-call-argument-newline: ["error", "consistent"]
    max-len: ["error", 160, {
        "ignoreComments": true,
        "ignoreUrls": true,
        "ignoreStrings": true,
        "ignoreTemplateLiterals": true,
        "ignoreRegExpLiterals": true
    }]
    max-lines-per-function: ["error", 500]
    max-lines: ["error", 640]
    max-statements: ["error", 20]
    no-console: ["off"]
    no-magic-numbers: ["off"]
    no-ternary: ["off"]
    no-use-before-define: ["error", "nofunc"]
    object-curly-spacing: ["error", "always"]
    object-property-newline: ["error", { "allowAllPropertiesOnSameLine": true }]
    one-var: ["error", "never"]
    padded-blocks: ["off"]
    prefer-destructuring: ["error", {
        "array": false,
        "object": false
    }, {
        "enforceForRenamedProperties": false
    }]
    quote-props: ["error", "as-needed"]
    sort-keys: ["off"]
    space-before-function-paren: ["error", {
        "anonymous": "never",
        "named": "never",
        "asyncArrow": "always"
    }]
